In [2]:
import torch
import numpy as np
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tkinter as tk
from tkinter import filedialog
import pandas_ta as ta
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, cohen_kappa_score
from statsmodels.stats.outliers_influence import variance_inflation_factor

# initialise tkinter window for file selection
root = tk.Tk()
root.wm_attributes('-topmost', 1)
root.withdraw()

# feature engineering and scaling
def prep(dataset):
    scaler = StandardScaler()

    # import macroecnomic data and parse to dataframe
    # replace each address path with appropriate path to load macroeconomic data 
    macro_path1 = r"C:\Users\samto\Desktop\Artefacts\unemployment.csv" 
    macro_path2 = r"C:\Users\samto\Desktop\Artefacts\disposable_income.csv"
    macro_path3 = r"C:\Users\samto\Desktop\Artefacts\cpi.csv"
    macro_path4 = r"C:\Users\samto\Desktop\Artefacts\FFR.csv"
    macro_path5 = r"C:\Users\samto\Desktop\Artefacts\mortgage.csv"
    macro_path6 = r"C:\Users\samto\Desktop\Artefacts\GVZ_History.csv"
    macro_path7 = r"C:\Users\samto\Desktop\Artefacts\OVX_History.csv"
    macro_path8 = r"C:\Users\samto\Desktop\Artefacts\VVIX_History.csv"
    macro_data1 = pd.read_csv(macro_path1)
    macro_data2 = pd.read_csv(macro_path2)
    macro_data3 = pd.read_csv(macro_path3)
    macro_data4 = pd.read_csv(macro_path4)
    macro_data5 = pd.read_csv(macro_path5)
    macro_data6 = pd.read_csv(macro_path6)
    macro_data7 = pd.read_csv(macro_path7)
    macro_data8 = pd.read_csv(macro_path8)

    # standardise date format and set date to index in stock price dataset
    dataset['Date'] = pd.to_datetime(dataset['Date'], dayfirst=True)
    dataset.set_index('Date', inplace=True)

    # set movement direction target, where 1 = rise and 0 = fall
    dataset['Target'] = np.where(dataset['Close'].shift(-1) > dataset['Close'], 1, 0)

    # standardise date format and set dates to index in all macroeconomic datasets
    macro_data1['Date'] = pd.to_datetime(macro_data1['Date'], dayfirst=True)
    macro_data1.set_index('Date', inplace=True)

    macro_data2['Date'] = pd.to_datetime(macro_data2['Date'], dayfirst=True)
    macro_data2.set_index('Date', inplace=True)

    macro_data3['Date'] = pd.to_datetime(macro_data3['Date'], dayfirst=True)
    macro_data3.set_index('Date', inplace=True)

    macro_data4['Date'] = pd.to_datetime(macro_data4['Date'], dayfirst=True)
    macro_data4.set_index('Date', inplace=True)

    macro_data5['Date'] = pd.to_datetime(macro_data5['Date'], dayfirst=True)
    macro_data5.set_index('Date', inplace=True)

    macro_data6['Date'] = pd.to_datetime(macro_data6['Date'])
    macro_data6.set_index('Date', inplace=True)

    macro_data7['Date'] = pd.to_datetime(macro_data7['Date'], dayfirst=False)
    macro_data7.set_index('Date', inplace=True)

    macro_data8['Date'] = pd.to_datetime(macro_data8['Date'], dayfirst=False)
    macro_data8.set_index('Date', inplace=True)

    # join all datasets
    merge_data1 = dataset.join(macro_data1, how='left').fillna(method='ffill')
    merge_data2 = merge_data1.join(macro_data2, how='left').fillna(method='ffill')
    merge_data3 = merge_data2.join(macro_data3, how='left').fillna(method='ffill')
    merge_data4 = merge_data3.join(macro_data4, how='left').fillna(method='ffill')
    merge_data5 = merge_data4.join(macro_data5, how='left').fillna(method='ffill')
    merge_data7 = merge_data5.join(macro_data7, how='left').fillna(method='ffill')
    merge_data8 = merge_data7.join(macro_data8, how='left').fillna(method='ffill')
    merge_final = merge_data8.join(macro_data6, how='left').fillna(method='ffill')

    # calculate technical indicators
    merge_final['RSI (14D)'] = ta.rsi(merge_final['Close'], length=14)
    merge_final['20 Day CCI'] = ta.cci(high=merge_final['High'], low=merge_final['Low'], 
                                    close=merge_final['Close'], length=20)
    merge_final['Williams %R'] = ta.willr(high=merge_final['High'], low=merge_final['Low'], 
                                        close=merge_final['Close'], length=14)
    merge_final['EMA (5D)'] = merge_final['Close'].ewm(span=5, adjust=False).mean()
    merge_final['MA50'] = merge_final['Close'].rolling(window=50).mean()

    # drop null values
    final_dataset = merge_final.dropna()

    # resample as monthly or weekly using resample('M') or resample('W-FRI'), for daily
    # predictions leave as is.
    time_shifted = final_dataset#.resample('M').asfreq().dropna()
    
    # select all features
    features = ['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume', 'CPI', 
                'Mortgage_rate', 'Unemp_rate', 'disposable_income','GVZ', 'OVX', 'VVIX', 
                'RSI (14D)', '20 Day CCI', 'Williams %R', 'EMA (5D)', 'MA50', 'FFR']
    
    # standardise data type and scale data
    time_shifted[features] = time_shifted[features].astype(float)
    time_shifted[features] = scaler.fit_transform(time_shifted[features])

    return time_shifted, scaler

# prompt to select dataset, import and parse to dataframe ready for processing 
file_path = filedialog.askopenfilename(parent=root, title="Select A File")
ticker = pd.read_csv(file_path)
ticker, scaler = prep(ticker)

ticker

C:\Users\samto\AppData\Local\Temp\ipykernel_16272\1033897956.py:106: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time_shifted[features] = time_shifted[features].astype(float)
C:\Users\samto\AppData\Local\Temp\ipykernel_16272\1033897956.py:107: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  time_shifted[features] = scaler.fit_transform(time_shifted[features])

,Open,High,Low,Close,Adj Close,Volume,Target,Unemp_rate,disposable_income,CPI,FFR,Mortgage_rate,OVX,VVIX,GVZ,RSI (14D),20 Day CCI,Williams %R,EMA (5D),MA50
Date,,,,,,,,,,,,,,,,,,,,
2009-09-18,-1.430574,-1.429777,-1.423754,-1.427001,-1.427001,1.376489,0,1.657579,-1.608203,-1.482353,-0.585650,1.456424,0.270120,-1.493092,1.117324,1.412609,1.348958,1.015335,-1.435223,-1.484032
2009-09-21,-1.426653,-1.433120,-1.430598,-1.431787,-1.431787,-0.519792,1,1.657579,-1.608203,-1.482353,-0.591876,1.456424,0.254290,-1.455507,1.243262,1.101440,0.912028,0.792402,-1.433957,-1.480216
2009-09-22,-1.431169,-1.430274,-1.425240,-1.425881,-1.425881,-0.355889,0,1.657579,-1.608203,-1.482353,-0.591876,1.456424,0.194489,-1.624331,1.518226,1.274180,0.923805,1.067482,-1.431143,-1.476714
2009-09-23,-1.425262,-1.421682,-1.428857,-1.435296,-1.435296,-0.064715,0,1.657579,-1.608203,-1.482353,-0.591876,1.456424,0.244323,-1.629260,1.402783,0.687948,0.717729,0.374115,-1.432408,-1.473467
2009-09-24,-1.434598,-1.434652,-1.437563,-1.440055,-1.440055,-0.301204,0,1.657579,-1.608203,-1.482353,-0.598102,1.456424,0.423140,-1.469062,0.987189,0.414658,0.307175,0.055231,-1.434840,-1.470916
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-07-23,2.118950,2.104272,2.130105,2.108394,2.108394,0.341921,0,-1.004953,0.939571,1.755746,2.633200,1.341485,-0.605202,-0.376635,-0.389731,0.477790,0.384198,-0.280665,2.120808,2.036117
2024-07-24,2.091963,2.073234,2.070486,2.050020,2.050020,1.145415,1,-1.004953,0.939571,1.755746,2.633200,1.341485,-0.598753,0.708398,-0.276387,-0.336836,-0.107772,-1.014472,2.098582,2.036914
2024-07-25,2.047737,2.094012,2.071656,2.059420,2.059420,1.006861,1,-1.004953,0.939571,1.755746,2.633200,1.341485,-0.619859,0.601189,-0.368741,-0.226293,-0.053028,-0.896300,2.086901,2.038091
2024-07-26,2.083885,2.130298,2.109291,2.135166,2.135166,0.678001,1,-1.004953,0.939571,1.755746,2.633200,1.341485,-0.427558,-0.000786,-0.440106,0.532788,0.379376,0.055882,2.104389,2.040502
2024-07-29,2.144648,2.122080,2.138151,2.137425,2.137425,-0.847018,0,-1.004953,0.939571,1.755746,2.633200,1.341485,-0.427558,-0.000786,-0.440106,0.552495,0.396678,0.026279,2.116802,2.042140

In [3]:
# perform vif test and display results
vif_ticker = pd.DataFrame()
features = ticker[['Close', 'Volume', 'CPI', 
                'Mortgage_rate', 'Unemp_rate', 'disposable_income','GVZ', 'OVX', 'VVIX', 
                'RSI (14D)', '20 Day CCI', 'Williams %R', 'MA50', 'FFR']]
vif_ticker["feature"] = features.columns

vif_ticker["VIF"] = [variance_inflation_factor(features.values, i)
                          for i in range(len(features.columns))]

vif_ticker

              feature         VIF
0               Close  361.921475
1              Volume    2.706974
2                 CPI   27.952566
3       Mortgage_rate    3.066348
4          Unemp_rate    3.319086
5   disposable_income   11.687196
6                 GVZ    2.378684
7                 OVX    2.452232
8                VVIX    3.037669
9           RSI (14D)    7.660635
10         20 Day CCI    7.316805
11        Williams %R    5.896363
12               MA50  372.954279
13                FFR    4.407593

In [4]:
# create LSTM model class with 4 lstm layers, dropout, and linear layer
class LSTM_Model(nn.Module):
    def __init__(self, input_layer, hidden_layer, output_layer, num_layers=4, dropout=0.3):
        super(LSTM_Model, self).__init__()
        self.hidden_layer = hidden_layer
        self.num_layers = num_layers
        self.lstm = nn.LSTM(input_layer, hidden_layer, num_layers, batch_first=True, dropout=dropout)
        self.dropout = nn.Dropout(dropout)
        self.linear_layer = nn.Linear(hidden_layer, output_layer)

    def forward(self, input_tensor):
        # initialize hidden state and cell state
        h0 = torch.zeros(self.num_layers, input_tensor.size(0), self.hidden_layer).to(input_tensor.device)
        c0 = torch.zeros(self.num_layers, input_tensor.size(0), self.hidden_layer).to(input_tensor.device)
        
        # pass through lstm layers
        out, _ = self.lstm(input_tensor, (h0, c0))
        
        # apply dropout
        out = self.dropout(out[:, -1, :])
        
        # pass through linear layer
        out = self.linear_layer(out)

        return out

# create sequences for input data and corresponding labels
def create_sequence(input_data, sequence_length):
    sequences = []
    for i in range(0, len(input_data) - sequence_length):
        sequence = input_data[i : i + sequence_length, :-1]
        label = input_data[i + sequence_length, -1]
        sequences.append((sequence, label))
    return sequences

# train the model with data provided
def trainer(model, train_data, loss_func, opt, epochs, fold, losses):
    model.train()
    for epoch in range(epochs):
        for sequence, labels in train_data:
            opt.zero_grad()
            sequence = sequence.clone().detach().float()
            labels = labels.clone().detach().float().view(-1, 1)
            y = model(sequence)
            
            # apply loss function and adam optimiser
            loss = loss_func(y, labels)
            loss.backward()
            opt.step()

        # calculate and print loss every 10 epochs
        if epoch % 10 == 1 or epoch == 99:
            print(f'Epoch {epoch} loss: {loss.item():.4f}')
            
            # insert loss values in dataframe for results
            new_row = pd.DataFrame({'Fold': [fold+1], 'Epoch': [epoch], 'Loss': [loss.item()]})
            losses = pd.concat([losses, new_row], ignore_index=True)
            
    return losses

# predict target values with trained model
def predictor(model, test_data):
    model.eval()
    predictions = []
    with torch.no_grad():
        for sequence, _ in test_data:
            sequence = sequence.clone().detach().float()
            y = model(sequence)
            batch_predictions = torch.sigmoid(y)

            # Convert predictions to tensor if they are float
            if isinstance(batch_predictions, float) or batch_predictions.ndimension() == 0:
                batch_predictions = torch.tensor([batch_predictions])

            batch_predictions = torch.round(batch_predictions)
            predictions.extend(batch_predictions.squeeze().tolist())
    
    return predictions

# create sequences with chosen predictor variables
sequence_length = 10
sequences = create_sequence(ticker[['Close', 'Volume', 'CPI', 'Mortgage_rate', 'Unemp_rate', 
                                    'disposable_income','GVZ', 'OVX', 'VVIX', 'RSI (14D)', 
                                    '20 Day CCI', 'Williams %R', 'MA50', 'FFR', 'Target']].values, sequence_length)

# initialise evalutation metric lists/dataframe and set number of splits
tscv = TimeSeriesSplit(n_splits=10)
accuracies = []
precisions = []
recalls = []
f1s = []
kappas = []
losses = pd.DataFrame(columns=['Fold', 'Epoch', 'Loss'])

# perform cross validation on given dataset with n number of folds
for fold, (train_index, test_index) in enumerate(tscv.split(sequences)):
    print(f'Fold {fold+1}')
    
    # initialise sequences
    train_sequences = [sequences[i] for i in train_index]
    test_sequences = [sequences[i] for i in test_index]
    
    # parse to dataloader for training/testing
    train_data = torch.utils.data.DataLoader(train_sequences, shuffle=True, batch_size=32)
    test_data = torch.utils.data.DataLoader(test_sequences, shuffle=False, batch_size=32)
    
    # initialise model, loss function and optimiser
    model = LSTM_Model(input_layer=14, hidden_layer=50, output_layer=1)
    loss_func = nn.BCEWithLogitsLoss()
    opt = optim.Adam(model.parameters(), lr=0.001, weight_decay=0.0001)
    
    # train model for set epochs and return loss values
    epochs = 100
    losses = trainer(model, train_data, loss_func, opt, epochs, fold, losses)
    
    # make predictions
    test_labels = [label for _, label in test_sequences]
    predictions = predictor(model, test_data)
    
    # calculate statistics for each epoch and fold
    accuracy = accuracy_score(test_labels, predictions)
    precision = precision_score(test_labels, predictions, zero_division=0)
    recall = recall_score(test_labels, predictions)
    f1 = f1_score(test_labels, predictions)
    kappa = cohen_kappa_score(test_labels, predictions)
    
    # append evaluation metrics to list for recording results
    accuracies.append(accuracy)
    precisions.append(precision)
    recalls.append(recall)
    f1s.append(f1)
    kappas.append(kappa)
    
    # print results at the end of each fold
    print(f'\nAccuracy: {accuracy:.4f}')
    print(f'Precision: {precision:.4f}')
    print(f'Recall: {recall:.4f}')
    print(f'F1: {f1:.4f}')
    print(f'Kappa: {kappa:.4f}\n')

# calculate average scores across all folds
avg_accuracy = np.mean(accuracies)
avg_precision = np.mean(precisions)
avg_recall = np.mean(recalls)
avg_f1 = np.mean(f1s)
avg_kappa = np.mean(kappas)

# calculate average scores across all folds
print(f'\nCross-Validation Results:')
print(f'Average Accuracy: {avg_accuracy:.4f}')
print(f'Average Precision: {avg_precision:.4f}')
print(f'Average Recall: {avg_recall:.4f}')
print(f'Average F1: {avg_f1:.4f}')
print(f'Average Kappa: {avg_kappa:.4f}')

Fold 1
Epoch 1 loss: 0.6849
Epoch 11 loss: 0.6907
Epoch 21 loss: 0.6397

KeyboardInterrupt:

In [12]:
# calculate rises and falls in given dataset
fall = (ticker.Target == 0).sum()
rise = (ticker.Target == 1).sum()

rise_per = (rise / (rise + fall)) * 100
fall_per = (fall / (rise + fall)) * 100

print(f'Number of days rising: {rise}')
print(f'Number of days falling: {fall}')

print(f'Rise % is: {rise_per:.2f}%')
print(f'Fall % is: {fall_per:.2f}%')

Number of days rising: 61
Number of days falling: 41
Rise % is: 59.80%
Fall % is: 40.20%

In [15]:
# initialise results dataframe
results = pd.DataFrame(columns=['Dataset', 'Average Accuracy', 'Average Precision', 
                                'Average Recall', 'Average F1', 'Average Kappa', 'Number of Rises', 
                                'Number of Falls', 'Rise %', 'Fall %'])

# fetch dataset name
datatset_name = (file_path.split('/')[-1].split('.')[0])

metrics = {'Dataset': datatset_name ,'Average Accuracy': avg_accuracy, 
           'Average Precision': avg_precision, 'Average Recall': avg_recall, 
           'Average F1': avg_f1, 'Average Kappa': avg_kappa, 'Number of Rises': rise, 'Number of Falls': fall, 
           'Rise %': rise_per, 'Fall %': fall_per}

# insert results into dataframe
export_results = results._append(metrics, ignore_index=True)

# join with loss values
export_results = pd.concat([export_results, losses], ignore_index=True)

export_results.set_index('Dataset', inplace=True)

# parse results to csv and save in Artefacts folder
# replace address path with desired destination path
export_results.to_csv(r"C:\Users\samto\Desktop\Artefacts\\" + datatset_name + '_results.csv')

export_results

,Average Accuracy,Average Precision,Average Recall,Average F1,Average Kappa,Number of Rises,Number of Falls,Rise %,Fall %,Fold,Epoch,Loss
Dataset,,,,,,,,,,,,
^NYA,0.6125,0.572857,0.668333,0.57486,0.143462,61,41,59.803922,40.196078,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,0.692703
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11,0.699558
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,21,0.690336
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,31,0.689003
...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,61,0.480847
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,71,0.472240
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,81,0.662616
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,91,0.496493
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,99,0.472894